name = "cloudflare"
main = "src/index.js"
compatibility_date = "2023-12-01"

# Configuração de rotas
routes = [
  { pattern = "worbyta.com/*", zone_name = "worbyta.com" }
]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = false



